[build-system]
requires = ["scikit-build-core>=0.10", "nanobind>=2.0"]
build-backend = "scikit_build_core.build"

[project]
name = "goddard"
authors = [
    {name = "Liem Dam-Quang", email="dq@liem.ca"}
]
version = "0.1.0"
description = "Rocket engine simulation toolkit"
readme = "readme.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
]
license = { file = "LICENSE" }
urls ={ Repository = "https://github.com/LiemDQ/goddard", Issues = "https://github.com/LiemDQ/goddard/issues"}
[project.optional-dependencies]
dev = ["pytest"]

[tool.scikit-build]
cmake.build-type = "Release"
wheel.packages = ["python/goddard"]
cmake.args = [
    "-Dgoddard_BUILD_PYTHON=ON",
    "-Dgoddard_ENABLE_SANITIZER_ADDRESS=OFF",
    "-Dgoddard_ENABLE_SANITIZER_UNDEFINED=OFF",
]
