import re
import yaml

class Nasa9Thermo:
    def __init__(self, temperature_ranges, data) -> None:
        self.temperature_ranges = temperature_ranges
        self.data = data
        self.model = "NASA9"
    
    def __repr__(self) -> str:
        return f"model:{self.model}\ntemperature ranges: {self.temperature_ranges}\ndata: {self.data}"

class ConstCpThermo:
    s0 = 0.0
    cp0 = 0.0 #these values are unused by NASA correlations
    def __init__(self, T0, h0) -> None:
        self.T0 = T0
        self.h0 = h0
        self.model = "constant-cp"
    
    def __repr__(self) -> str:
        return f"model:{self.model}\nT0:{self.T0}\nh0:{self.h0}"

class CtSpecies:
    def __init__(self, name: str, composition, thermo) -> None:
        self.name = name
        self.composition = composition
        self.thermo = thermo
    
    def get_dict(self):
        thermo_dict = vars(self.thermo)
        if "temperature_ranges" in thermo_dict:
            thermo_dict["temperature-ranges"] = thermo_dict.pop("temperature_ranges")
        return {"name": self.name, "composition": self.composition, "thermo": thermo_dict}


def parse_name(line: str):
    name_and_id = line.split()
    return name_and_id[0]

def parse_physical_params(params: str):
    values = params.split()

    # first value is False for gases, True otherwise
    # second value is molecular weight
    # third value is enthalpy of formation at 298.15K
    return bool(values[0]), float(values[1]), values[2]

def parse_coeffs(file):
    def parse_coeff_value(coeff_str: str):
        is_negative: bool = coeff_str.startswith("-")
        value = float(coeff_str[1:12])
        decimal = int(coeff_str[13:])
        final_value = value* 10**decimal
        if is_negative:
            final_value *= -1
            
        return final_value


    line1 = file.readline()
    l1_entries = line1.split()
    T0 = float(l1_entries[0])
    T1 = float(l1_entries[1])
    deltaH = l1_entries[-1] #to my knowledge, this is not used by Cantera.

    coeffs = []
    line2 = file.readline()
    for n in range(5):
        begin = n*16
        end = (n+1)*16
        coeffs.append(parse_coeff_value(line2[begin:end]))

    line3 = file.readline()
    for n in range(5):
        if n == 2: #skip 3rd entry
            continue
        begin = n*16
        end = (n+1)*16
        coeffs.append(parse_coeff_value(line3[begin:end]))
    
    return T0, T1, coeffs

def parse_formula(formula: str):
    element_dict = {}
    elements = formula.split()
    current_element = elements[0]
    for element in elements[1:]:
        #separate the numbers from the letters
        split = re.split('([a-zA-Z]+)', element)
        # print(split)
        if float(split[0]) == 0:
                break

        element_dict[current_element] = float(split[0])
        if len(split) == 1:
            break
        else:
            current_element = split[1]
    
    # print(element_dict)
    return element_dict


def parse_const_cp(file):
    #get reference temperature
    T0 = float(file.readline().split()[0])
    return T0


def parse_species(file) -> CtSpecies:
    name = parse_name(file.readline())
    line = file.readline()
    num_intervals = int(line[0:2])
    formula = parse_formula(line[10:50])
    _,_,h0 = parse_physical_params(line[50:])
    h0 += " J/mol"

    if num_intervals == 0:
        T0 = parse_const_cp(file)
        thermo = ConstCpThermo(T0, h0)
    else:
        temp_range = []
        coeff_data = []
        for n in range(num_intervals):
            T0, T1, coeffs = parse_coeffs(file)
            temp_range.append(T0)
            coeff_data.append(coeffs)
            if n == num_intervals - 1:
                #avoid repeats of temperature range values
                #otherwise, all intermediate temperature values would appear twice
                temp_range.append(T1)
        thermo = Nasa9Thermo(temp_range, coeff_data)
    
    return CtSpecies(name, formula, thermo)

def reached_last_line(file) -> bool:
    pos = file.tell()
    is_last = file.readline().startswith("END REACTANTS")
    file.seek(pos)
    return is_last

if __name__ == "__main__":
    filename = "./nasa9.dat"
    results = []
    with open(filename, 'r') as f:
        #skip gases and condensed species
        while not f.readline().startswith("END PRODUCTS"):
            continue
        
        while not reached_last_line(f):
            results.append(parse_species(f))

    output_file = "./nasa_reactants.yaml"
    results_converted = list(map(lambda a: a.get_dict(), results))
    with open(output_file, 'w') as f:
        f.write("# Autogenerated by parse_nasa_data.py.\n# Do not edit manually.\n\n")
        f.write("species:\n")
        f.write(yaml.safe_dump(results_converted, default_flow_style=False))
